In [1]:
import numpy as np

# numpyで1から値を計算していく

In [6]:
x=np.array([[[1],[2],[3]]])
x

array([[[1],
        [2],
        [3]]])

In [8]:
X=np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [10]:
Xt=X.T
Xt

array([[1, 3],
       [2, 4]])

In [12]:
X_inv=np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
XX_inv=np.dot(X,X_inv)
XX_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [19]:
X=np.array([[1,2,3],[1,2,5],[1,3,4],[1,5,9]])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [23]:
y=np.array([[1],[5],[6],[8]])
y

array([[1],
       [5],
       [6],
       [8]])

In [24]:
Xt=X.T
Xt

array([[1, 1, 1, 1],
       [2, 2, 3, 5],
       [3, 5, 4, 9]])

In [26]:
XtX=np.dot(Xt,X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [28]:
XtX_inv=np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [30]:
Xty=np.dot(Xt,y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [33]:
w=np.dot(XtX_inv,Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# sckitlearnを用いて実際に値を求める

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
model=LinearRegression()

In [37]:
model.fit(X,y
         )

LinearRegression()

In [38]:
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [39]:
model.intercept_

array([-0.14285714])

In [40]:
model.score(X,y)

0.6923076923076925

In [41]:
x=np.array([[1,2,3]])

In [44]:
y_pred=model.predict(x)
y_pred

array([[3.]])